apiVersion: v1
kind: Service
metadata:
  name: stirrup-splash
  labels:
    app.kubernetes.io/name: stirrup-splash
    app.kubernetes.io/part-of: stirrup
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: stirrup-splash
  ports:
    - name: http
      port: 80
      targetPort: http
